### ISSUE TITLE
omitempty failed(runtime error) with ptr

### ISSUE THREAD

**Issue by TWT233** [Trim21/go-phpserialize#13]
# Description

testcase:
```
	{
		Name: "omitempty ptr",
		Data: struct {
			V *string `php:",omitempty"`
			D *string `php:",omitempty"`
		}{
			D: new(string),
		},
		Expected: ``,
	},
```

runtime error OOM raised

## Environment

- language version:  1.17
- app/lib/repo version: branch: master

## How to reproduce

add 

## Expectations

no re

## Actual result

runtime error raised

**Comment by Trim21** [comment]
我去，测试了一下系统崩掉了

**Comment by Trim21** [comment]
好像有点麻烦，晚点修

**Comment by Trim21** [comment]
草，才发现忘记检查是否导出的tag了（

**Comment by Trim21** [comment]
现在这个修复办法还是太丑陋了，而且感觉有潜在的bug没解决。

不过暂时能用了
