### ISSUE TITLE
How does this compare to elliotchance/phpserialize?

### ISSUE THREAD

**Issue by nickchomey** [trim21/go-phpserialize#53]
The elliotchance/phpserialize package already exists for this purpose. I'm curious what this package does differently? Thanks!

**Comment by trim21** [comment]
There are severial serialized type in phpserialize, for example, php arrar are serailized with `a` prefix, and php object are serialized with `O` prefix.

`elliotchance/phpserialize` can only encode map to php array, and can only decode php array to go map. all go struct will be encoded as php object.

This project can decode all php array, php object and php class to go struct, and encode go map/array/slice/struct to php array only.


There is also a class type (`C`) in php serialized result, and it's not supported in this project, I don't know if `elliotchance/phpserialize` support it.

**Comment by trim21** [comment]
make sence. This package is created to help me migrate some legacy package, it's not designed for all use cases
