### ISSUE TITLE
Inquiry About Upcoming Release of Version 0.1.0

### ISSUE THREAD

**Issue by slashformotion** [trim21/go-phpserialize#54]
Hi @trim21 ,

I hope this message finds you well.

I am writing to inquire about the anticipated release date for version 0.1.0 of your library. I am particularly interested in this update as it will provide compatibility with Go 1.23.

Your work on this library has been very valuable, and I appreciate all the effort you put into maintaining and improving it. Any information you can provide regarding the release timeline would be greatly appreciated.

Thank you for your time and assistance.

Best regards,
Théophile Roos

**Comment by trim21** [comment]
If you worry about compatibility with Go 1.23, v0.0.22 still work on go v1.23, golang shutting down `//go:linkname` means library can't link to more internal function in the furure, but current linkname still works, at least in go1.23

**Comment by trim21** [comment]
OK, I fotget I disabllw v0.0.x on go 1.23 version, I'll release a v0.0.23 now

**Comment by slashformotion** [comment]
Thanks !
